### ISSUE TITLE
Missing KML-enabled musl libc

### ISSUE THREAD

**Issue by dizz** [hckuo/Lupine-Linux#37]
Hi,
In the paper there are references to a KML-enabled musl libc. There are also references to it in the code within the repository. Can this modified code or the patch to the library be provided?

Thanks,
Andy

**Comment by hckuo** [comment]
https://github.com/hckuo/Lupine-Linux/blob/master/scripts/libc.so

**Comment by dizz** [comment]
Hey Austin - yes I know of that but it is the binary of the MUSL libc. Is the patch for code or the modified files available?

**Comment by dizz** [comment]
Maybe @djwillia knows seeing there are [refs to his musl workspace](https://github.com/hckuo/Lupine-Linux/blob/0aa6a6739ea00e153eee9d4fffd5048af5b7c4a0/musl_test/Makefile#L3)?

**Comment by hckuo** [comment]
I can't locate the exact path but this is the snippet we have.
```
- __asm__ __volatile__ ("syscall" : "=a"(ret) :
+ __asm__ __volatile__ ("call *%1" : "=a"(ret) : "r"(__kml),
"a"(n), "D"(a1), "S"(a2),
"d"(a3), "r"(r10), "r"(r8),
"r"(r9) : "rcx", "r11", "memory");
```

**Comment by dizz** [comment]
Great! Thanks @hckuo 😊 Might you know the line(s)? Seems there's a few locations that grep reveals:

```
musl on master
❯ grep -rin '__asm__ __volatile__ ("syscall" : "=a"(ret) :' ./
.//arch/x32/syscall_arch.h:10:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n) : "rcx", "r11", "memory");
.//arch/x32/syscall_arch.h:17:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1) : "rcx", "r11", "memory");
.//arch/x32/syscall_arch.h:24:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2)
.//arch/x32/syscall_arch.h:32:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x32/syscall_arch.h:42:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x32/syscall_arch.h:53:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x32/syscall_arch.h:65:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x86_64/syscall_arch.h:7:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n) : "rcx", "r11", "memory");
.//arch/x86_64/syscall_arch.h:14:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1) : "rcx", "r11", "memory");
.//arch/x86_64/syscall_arch.h:21:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2)
.//arch/x86_64/syscall_arch.h:29:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x86_64/syscall_arch.h:38:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x86_64/syscall_arch.h:48:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
.//arch/x86_64/syscall_arch.h:59:	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
```

**Comment by dizz** [comment]
Ok - my own answer😊 

The patch is applied to the inline function at [line 59 of syscall_arch.h](https://git.musl-libc.org/cgit/musl/tree/arch/x86_64/syscall_arch.h#n59). I'll assemble a simple patch and share as. a PR.

**Comment by dizz** [comment]
So here is the patch ([musl-kml.patch.txt](https://github.com/hckuo/Lupine-Linux/files/4608887/musl-kml.patch.txt)). I won't do a PR right now as there's one doubt. In the patch snippet that you supplied, @hckuo, there's an important variable `_kml`. From the snippet it's unclear its type. While the patch applied to MUSL compiles (no big surprise), I'm not sure that the type (`unsigned long`) is correct. 

Can you @hckuo or someone else validate the selected type based on the original patch?

**Comment by hckuo** [comment]
@djwillia

**Comment by djwillia** [comment]
Sorry for the delay, @dizz ; I put a PR in with my patch to musl libc that we used for the experimentation.  The `__kml` variable in question is actually `extern unsigned long __sysinfo;`, which is exposed through the kernel vsyscall/vdso mechanism.  It's how KML (in the kernel) tells the libc (in the "userspace") where the system calls are.

**Comment by dizz** [comment]
Ah! yes that PR is much more involved that what I hacked together! 😊 
Thanks @djwillia !

**Comment by hckuo** [comment]
#38

**Comment by a74731248** [comment]
when I try to verify libc invoke `call` instead of `syscall`, I try to modify the `syscall_arch.h` as follow: 
```
static __inline long __syscall0(long n)
{
	unsigned long ret;
#ifdef KML
    if (__sysinfo) {
        printf("invoke call: call %ld\n", __sysinfo);
        __asm__ __volatile__ ("call *%1" : "=a"(ret) : "r"(__sysinfo), "a"(n) : "rcx", "r11", "memory");
        return ret;
    }
#endif
	__asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n) : "rcx", "r11", "memory");
    return ret;
}
```
after I recompile it, I run it with that command in Lupine: `/trusted/libc.so /trusted/lat_syscall -N 100 read`. I find that it does not run the code in `#ifdef KML` section, because it does not print any information like "invoke call xxx"  It's where I did wrong?
@djwillia @dizz
