### ISSUE TITLE
Relating lupine `configs/*` to paper

### ISSUE THREAD

**Issue by bbros-dev** [hckuo/Lupine-Linux#39]
Apologies for being obtuse.  It is not clear to me which config files in this repo are lupine-base and which are lupine-general (I expect there will be kml/nokml variants)?

**Comment by hckuo** [comment]
lupine-base:https://github.com/hckuo/Lupine-Linux/blob/master/configs/lupine-djw-kml.config
lupine-general = lupine-base + all configs from configs/apps/

**Comment by hckuo** [comment]
Please refer to this script: https://github.com/hckuo/Lupine-Linux/blob/master/scripts/build-kernels.sh
You will build all kernels that we used in the paper.
