### ISSUE TITLE
Compatibility with QEMU/KVM

### ISSUE THREAD

**Issue by hlef** [hckuo/Lupine-Linux#44]
Is Lupine currently compatible with QEMU/KVM? Current configurations seem to work only on Firecracker.

**Comment by hlef** [comment]
It seems that a few configuration options are missing to support `virtio-blk` drives:
```
CONFIG_PCI=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_BLK_SCSI=y
```
This one might also be needed:
```
CONFIG_VIRTIO_PCI_LEGACY=y
```

**Comment by Moses20** [comment]
Same problem here.

@hlef were you able get it to run on QEMU/KVM? If so, could you comment the line command in here?

**Comment by hlef** [comment]
Yes, I managed to get it running on QEMU/KVM. You need to use the compressed kernel (Firecracker uses uncompressed kernels).

You can pass the usual ext2 filesystem using `-drive` (`virtio-blk-pci`, format `raw`).

For networking, the usual `tap` works.

For the kernel command line, pass something like
```
root=/dev/vda rw console=ttyS0 init=/guest_start.sh /bin/something
```

**Comment by Moses20** [comment]
If I understand you correctly, I have to compress the `vmlinux` with `gzip` in order for QEMU to run the kernel.

So I executed the following command:
`sudo qemu-system-x86_64  -nographic -kernel vmlinux.gz \
-drive "file=$FILE.ext2,format=raw,if=none,id=hd0"  \
-device virtio-blk-pci,id=blk0,drive=hd0,scsi=off \
-append "console=ttyS0 root=/dev/vda init=/bin/bash"`

Sadly, this command gets me stuck in "Booting from ROM..".

As you can tell, I am fairly new to QEMU and thankful for any help.

**Comment by hlef** [comment]
Oh, no, it's not only a matter of compressing the image, you should use `vmlinuz-4.0.0` instead of `vmlinux`. :-)

Otherwise it looks mostly okay.

**Comment by Moses20** [comment]
Thank you, the unikernel is up and running now.

Just one little problem: I want to be able to talk to the guest from outside the host. I tried setting up a tap, where the tap and interface are added to a bridge.

And then running Qemu with following two flags:
```
-netdev tap,id=mynet0,ifname=tap1,script=no 
-device virtio-net-pci,netdev=mynet0,id=nic0  
```

Do I have to do some extra stuff besides executing the 'guest_net.sh' to get access to my local network?

**Comment by hlef** [comment]
No, it should work like that.
