### ISSUE TITLE
Broken with recent Redis releases

### ISSUE THREAD

**Issue by hlef** [hckuo/Lupine-Linux#45]
It seems that Lupine doesn't work with recent Redis releases. The most recent release I managed to run with the currently available configuration is 5.0.4 (using the `redis:5.0.4-alpine` Docker container image).

**Comment by Moses20** [comment]
Have you got redis to run on QEMU/KVM?

**Comment by hlef** [comment]
Yes, you can check your artifact evaluation repository: https://github.com/unikraft/eurosys21-artifacts/tree/master/experiments/fig_12_redis-perf

**Comment by Moses20** [comment]
Where is the paper?

**Comment by hlef** [comment]
This is a little bit out of scope, but the paper has not been released yet, probably in the coming weeks.

**Comment by hckuo** [comment]
Thank you for the interest for Lupine. I think additional config options are needed to run redis.
