### ISSUE TITLE
KML kernel on Firecracker fails to start

### ISSUE THREAD

**Issue by vaibhavkulkarni** [hckuo/Lupine-Linux#48]
KML kernel on Firecracker fails to start with the following message:

> EXT2-fs (vda): error: ext2_lookup: deleted inode referenced: 1228803
> cp: can't stat '/trusted/nginx': I/O error

Root cause the is `cp` command in `guest_start.sh` where all the respective executables get copied to `/trusted` 

Any idea why we need this? Why not run directly from `/usr/sbin`?

**Comment by hckuo** [comment]
kernel recognizes `/trusted` to run in KML mode.
And your problem is actually a corrupted disk.
